### ISSUE TITLE
Does this paper note the previous Mamba paper?

### ISSUE THREAD

**Issue by Dibbidy** [GraphMamba/GMN#1]
https://arxiv.org/abs/2402.00789 - Graph-Mamba: Towards Long-Range Graph Sequence Modeling with Selective State Spaces

**Comment by GraphMamba** [comment]
Thank you very much for sharing this impressive work. We just learned about this work. Our work has been submitted before Feb 1 and the current version is our submission draft. We will make sure to properly discuss and credit this work in our next version.
